"""add audits

Revision ID: 2459e12e1b74
Revises: 43f803f2d8f4
Create Date: 2026-10-03 20:02:57.094071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2459e12e1b74'
down_revision: Union[str, Sequence[str], None] = '43f803f2d8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('authors', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('authors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('authors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'authors', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'authors', 'users', ['updated_by'], ['id'])
    op.add_column('books', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    op.add_column('loan', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('loan', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('loan', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('loan', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'loan', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'loan', 'users', ['updated_by'], ['id'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'loans',
                    foreign_keys='LoanDatabase.user_id')
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'updated_at')
    op.drop_column('loan', 'created_at')
    op.drop_column('loan', 'updated_by')
    op.drop_column('loan', 'created_by')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'updated_by')
    op.drop_column('books', 'created_by')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'updated_at')
    op.drop_column('authors', 'created_at')
    op.drop_column('authors', 'updated_by')
    op.drop_column('authors', 'created_by')
    # ### end Alembic commands ###
